name: Create Archive
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Archive Release
      uses: thedoctor0/zip-release@master
      with:
        filename: 'effective-less-css.zip'
        exclusions: '*.git* /*node_modules/* .editorconfig'
    - uses: actions/upload-artifact@master
      with:
          name: effective-less-css.zip
          path: effective-less-css.zip
